### PR TITLE
Added Kusk Gateway

### PR DESCRIPTION
**Pull request by olensmar**
also added a gateway category in line with #370

### CODE REVIEW

**Review by darrelmiller — APPROVED** [review]

**Comment by darrelmiller** [comment]
@olensmar  Thanks for this submission. The project looks very interesting.  Are there other tools in the list that would fit under this new `gateway` category?

**Comment by aabedraba** [comment]
@darrelmiller here is a list of API Gateways that have support of OpenAPI in some way:
Amazon API Gateway: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html
Google API Gateway: https://cloud.google.com/api-gateway/docs/openapi-overview
Kong plugin: https://github.com/Kong/openapi2kong 
Zuplo: https://zuplo.com/docs/developer-portal/open-api/

**Comment by olensmar** [comment]
@darrelmiller of these both Zuplo and Kong are already in the list - should I add this tag to them to should we wait for them to it themselves?

**Comment by darrelmiller** [comment]
@olensmar  If you think they fit the tag.  Add them and I will merge this PR.

**Comment by olensmar** [comment]
Hi @darrelmiller - I've added the tag to Zuplo, Kong and Fusio also - please merge at will!

**Comment by darrelmiller** [comment]
Thank you!  And sorry for the delay.  My vacation was longer than usual  :-)

**Comment by olensmar** [comment]
no worries - thanks for merging!

**Pull request merged**
