### PR TITLE
Adds sdk tool; Openapi Json Schema Generator

### PR DESCRIPTION
**Pull request by spacether**
Adds sdk tool; Openapi Json Schema Generator

It generates python clients and is at https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

This generator works with 3.0.0 to 3.0.3 spec documents and 3.1.0 featured are being worked on. 

Could this PR be reviewed to get it added?
Thank you!

### CODE REVIEW

**Comment by daveshanley** [comment]
This looks good to me.

**Comment by daveshanley** [comment]
Except, before merging.. it looks like this is a Kotlin project, not python?

**Comment by spacether** [comment]
It is a java tool which generates python code. It can also be invoked bis docker so the end user doesn't need Java installed

**Comment by spacether** [comment]
Thank you!

**Pull request merged**
