### PR TITLE
Added MrinDoc to the list of API Docs

### PR DESCRIPTION
**Pull request by mrin9**
A new API doc viewer

### CODE REVIEW

**Comment by philsturgeon** [comment]
This website doesn’t load at all on mobile. Does it work on desktop?

**Comment by mrin9** [comment]
For now it works only in Desktop, To make it responsive is in the plans. 
Check out [ReadMe](https://github.com/mrin9/OpenAPI-Viewer/blob/master/README.md) ToDo list to get a glimpse of whats planned ahead

**Comment by mrin9** [comment]
@philsturgeon were you able to verify the app over the desktop ?

**Comment by philsturgeon** [comment]
OHHHH I see, ok so the `link` is to the actual console, not a homepage about the console. Ok. 

This looks good, but maybe you could use a default API which does not require authentication? I was unable to confirm any actual requests on the try logic because they were all unauthenticated errors. 

Also, should we add a new category? Consoles? I'd like to see more of these, or see them improve. I believe ReDoc will soon be getting this too, putting it in both the Documentation and Console categories, so maybe this could also be in both?

**Pull request merged**
