### PR TITLE
swagman mock and convert

### PR DESCRIPTION
**Pull request by codeasashu**
Swagmanmock provides a python tool (and module) to convert postman collection to openapi spec. Additionally, this tool also mocks the spec using postman examples and documents them

### CODE REVIEW

**Comment by philsturgeon** [comment]
Hey @codeasashu. This seems like a brand new project but you're using the name Swagger? It has not been called Swagger since 2016, so now would be a good time to change it before folks start using it. It looks really really useful, but... we don't want to keep perpitrarting the confusion over the naming. It's OpenAPI, so maybe you could call it apiman, openman, postapi, openapi-to-postman, etc.?

**Comment by codeasashu** [comment]
`openman` seems nice. Refactoring in a moment.

**Comment by codeasashu** [comment]
Sorry, I had commited with different user, hence had to force push. I've changed every instance of "Swagman" with "openman", hence the word "swagger" has been dropped

**Comment by philsturgeon** [comment]
Awesome! Seeing as its still really new, lets revisit this PR in a few weeks. It'll give you time to get up on Pip, flesh things out a bit. :)

**Comment by philsturgeon** [comment]
Seems like this has not got past a few commits. If this is being actively developed and improved let me know, otherwise I'll keep it out for now.

**Pull request closed without merging**
