### PR TITLE
New Tool and new category

### PR DESCRIPTION
**Pull request by JustSteveKing**
This PR adds a new tool that I use [Treblle](https://www.treblle.com/) as well as a new category for monitoring tools

### CODE REVIEW

**Review by daveshanley — APPROVED** [review]
LGTM

**Comment by darrelmiller** [comment]
It is not clear from the website how Treblle uses OpenAPI for monitoring APIs?  The only reference I could find on the website for OpenAPI was related to documentation and it has a link to the wrong website for the specification https://docs.treblle.com/en/dashboard/api-documentation  It should be https://spec.openapis.org/oas/latest.html not https://swagger.io/specification

**Comment by daveshanley** [comment]
When I reviewed the tooling, I noticed certain features that can only exist with OpenAPI, like this: 

https://www.treblle.com/features/auto-generated-api-docs

Based on this, this is a legit link; even if OpenAPI is not its primary focus, it does seem to have solid support.

**Comment by daveshanley** [comment]
Will merge once the conflict is resolved

**Pull request merged**
