### PR TITLE
Add entry for RESTler fuzzer.

### LINKED ISSUE #261: add RESTler fuzzer to data validators
Hello,

I noticed that ApiFuzzer is listed under validation tools, and wanted to suggest also adding the RESTler fuzzer to the list: https://github.com/microsoft/restler-fuzzer 

RESTLER's description from the README: 

RESTler is the first stateful REST API fuzzing tool for automatically testing cloud services through their REST APIs and finding security and reliability bugs in these services. For a given cloud service with an OpenAPI/Swagger specification, RESTler analyzes its entire specification, and then generates and executes tests that exercise the service through its REST API.

### PR DESCRIPTION
**Pull request by marina-p**
Add entry for RESTler fuzzer.
Closes #261

### CODE REVIEW

**Comment by marina-p** [comment]
After going through all the categories, the 'security' tag was the closest fit. 

For language I put 'Any' since it is a command line tool, let me know if there is a more appropriate label.

**Comment by matthewtrask** [comment]
hm why did the whole tools.yml file get updated?

I think for language, putting CLI/Bash may be best?

**Comment by marina-p** [comment]
Thanks, will fix shortly

**Comment by marina-p** [comment]
I believe the whole file updating issue is now fixed.

**Comment by darrelmiller** [comment]
@marina-p We can merge this entry.  However the readme of the project uses the term "Swagger" when it means OpenAPI.  The contributing guidelines say,

> Try and avoid using the word "Swagger" unless you work for SmartBear and are literally talking about the Swagger toolsuite. It's been called OpenAPI for years now.

**Review by inverse — APPROVED** [review]

**Comment by mikekistler** [comment]
@darrelmiller The RESTler README has been updated to use "OpenAPI" as requested.

**Comment by darrelmiller** [comment]
Thank you @mikekistler

**Pull request merged**
