### PR TITLE
Update tools.yml: mitmproxy2swagger

### PR DESCRIPTION
**Pull request by j13k**
Added tool stanza for mitmproxy2swagger

### CODE REVIEW

**Comment by j13k** [comment]
I've noticed that mitmproxy2swagger also has some functionality in common with tools in the 'Leaerning' category. Would it be worth adding to that one as well?

**Comment by darrelmiller** [comment]
@j13k Sorry, we can't add a tool that has Swagger in the name to this list unless it comes from Smartbear.  They are the registered trademark owners of Swagger.

**Comment by daveshanley** [comment]
> @j13k Sorry, we can't add a tool that has Swagger in the name to this list unless it comes from Smartbear. They are the registered trademark owners of Swagger.

+1 on this. 

Rename the tool to mitmproxy2openapi and it changes the game.

**Comment by j13k** [comment]
Thanks for the update. I don't have any involvement in that project; just found the tool useful and thought others might as well.

**Pull request closed without merging**
