### PR TITLE
Adding visual studio api-studio (resolved merge conflicts)

### PR DESCRIPTION
**Pull request by arbs-io**
Adding visual studio "Api Studio"

Api Studio is a productivity extension for Microsoft Visual Studio. The extension bridges the role of architect and developer, providing rapid prototyping and promoting industry best practices.

MarkeetPlace: https://marketplace.visualstudio.com/items?itemName=AndrewButson.ApiStudio
Repo: https://github.com/arbs-io/api-studio-visualstudio

### CODE REVIEW

**Comment by arbs-io** [comment]
New pull request with resolved conflicts

**Comment by darrelmiller** [comment]
It is not really clear how this tool is related to OpenAPI

**Comment by arbs-io** [comment]
> It is not really clear how this tool is related to OpenAPI

Hi @darrelmiller 
The tool uses a designer and dsl, It provides a standard approach and will provide default response codes and parameters using RESTful semantics. Once the Arch/Dev completes the design the tool generates code (currently csharp, but i will be adding python, typescript and go soon). The solutions are fully functional and include an OpenAPI specification, including swagger-ui when executed.

**Comment by daveshanley** [comment]
This is not really an OpenAPI tool.

**Pull request closed without merging**
