### PR TITLE
Add Aptori

### PR DESCRIPTION
**Pull request by travisnewhouse**
Please add [Aptori](https://aptori.dev/) to the tools list.

Aptori is an application vulnerability scanner and REST API validator designed for Developers and DevSecOps teams. Utilizing OpenAPI v2 or v3 definitions, it automatically generates test scenarios and conducts comprehensive scans.

### CODE REVIEW

**Comment by travisnewhouse** [comment]
What is required to have this pull request accepted?

**Comment by mishushakov** [comment]
No signup?

**Comment by travisnewhouse** [comment]
> No signup?

Can you elaborate?

**Comment by mishushakov** [comment]
There's no way to sign up or to try it out. Maybe I'm doing something wrong, but I only see a contact form

**Comment by travisnewhouse** [comment]
> There's no way to sign up or to try it out. Maybe I'm doing something wrong, but I'm only seeing a contact form

Please fill out the contact form and we will be happy to get in touch with you!

**Comment by philsturgeon** [comment]
No contact-form-only signups please. Thank you!

**Pull request closed without merging**
