### PR TITLE
Merged with latest changes of the _data/tools.yaml and compiled again to avoid conflicts

### PR DESCRIPTION
**Pull request by robarago**
Please, consider this changes. Sorry for the missunderstanding

### CODE REVIEW

**Comment by daveshanley** [comment]
These tools are not focused on OpenAPI, from what I can tell, they use other projects for OpenAPI parsing and generating.

**Comment by robarago** [comment]
> These tools are not focused on OpenAPI, from what I can tell, they use other projects for OpenAPI parsing and generating.

Thank you very much for considering my contribution and also for taking the time to evaluate them, Dave.

I'd like to explain a little more how my tools, DRAIG and DRAIG-CAR *do focus* a lot on OpenAPI and how they use other projects to clarify your appreciation.

DRAIG is a custom OpenAPI generator and, like all the custom generators, require `openapi-generator` to run as a dependency. It is, of course, totally focused on OpenAPI, since it generates code based on the definition file (yaml), but also squeezes all the potential of the standard by using vendor extensions extensively.

DRAIG-CAR is both a CLI and a REPL based on NodeJS. It's in fact a CLI editor of a OpenAPI definition file, so it's indeed *focused* on OpenAPIv3, can't work without the standard. It requires other tools, it's true, to generate code. Of course, it uses DRAIG to generate the code with `openapi-generator` but other requirements are standard npm dependencies, libraries, `npm` itself that you require also to install the tool, not _projects_. I really don't see how this is different from other tools generating code from OpenAPI. Also, `docker` requirement is *optional*, so you can test the tools both in Windows and in GNU/Linux.

I expect to have cleared a little your doubts and, if you have some other concern, please let me help you to clear it out, I'll very please to know from you to explain any particular about my tools.

Thank you again.
Regards,
Roberto.

**Comment by daveshanley** [comment]
Thanks for the clarification Roberto.

I think if you bump up the description of the two entries, it would help people understand more. It helped me, and if you can add a little more color to both entries that explains like you have above, I can approve it.

**Comment by robarago** [comment]
I've done the changes here: https://github.com/apisyouwonthate/openapi.tools/pull/420 and I'll wait for further instructions.

Thanks again

**Pull request closed without merging**
