### PR TITLE
Add lapidary.

### PR DESCRIPTION
**Pull request by rafalkrupinski**

### CODE REVIEW

**Comment by AndrewWalsh** [comment]
Hi @rafalkrupinski ,

Thank you for the submission. 

Screenshot 2024-05-29 at 19 56 05

This looks like an interesting project. My understanding is that it shares come conceptual relation with the ambitions of TypeSpec, but concentrated on Python. An alternative DSL to that of OpenAPI, with the intention of generating Python-based server code. This is commendably ambitious.

However at this stage, I acknowledge that the project has yet to see much adoption. Its interoperability with the OpenAPI specification is also unclear, as in the above picture. We're focused on the OpenAPI ecosystem.

I would encourage you to resubmit when these factors are addressed however, and I acknowledge you're tackling a very difficult problem.

**Comment by rafalkrupinski** [comment]
> My understanding is that it shares come conceptual relation with the ambitions of TypeSpec

I'm not sure what TypeSpec is trying to achieve...

> An alternative DSL to that of OpenAPI, with the intention of generating Python-based server code.

No, it's client code. Lapidary is a library that delivers DSL for writing Web API clients, while lapidary-render is generator of such code from OpenAPI documents.

Most of OpenAPI 3.0 is implemented, 3.1 is planned.

**Comment by AndrewWalsh** [comment]
Re-submissions are always welcome, and this information would be great to include in the next. We're open to contributions to the OpenAPI ecosystem, so please don't take the decline as anything negative :).

**Comment by rafalkrupinski** [comment]
Would you rather add lapidary - a DSL that attempts to have similar capabilities to OpenAPI in terms of Web API description, lapidary-render that directly handles OpenAPI documents or both?
lapidary-render generates code that uses lapidary, but lapidary is also usable directly for writing clients by hand.

**Comment by AndrewWalsh** [comment]
@rafalkrupinski The main issue I saw was unclear community adoption. Please see our contributor guideline below. I may advise gaining traction first.

https://github.com/apisyouwonthate/openapi.tools/blob/main/CONTRIBUTING.md

**Comment by AndrewWalsh** [comment]
@rafalkrupinski

**Pull request closed without merging**
