### PR TITLE
Add rest.wiki

### PR DESCRIPTION
**Pull request by InventivetalentDev**
Just a very simplistic renderer for OpenAPI definitions :)  
https://rest.wiki/
https://github.com/InventivetalentDev/openapi-viewer

### CODE REVIEW

**Comment by darrelmiller** [comment]
Is this more than a hosted and themed SwaggerUI?

**Comment by daveshanley** [comment]
This is not an OpenAPI tool, it's not a tool - it's a theme for Swagger UI.

**Comment by InventivetalentDev** [comment]
how do you see this as a theme?

quoting the Documentation "tool type":
"Render API Description as HTML (or maybe a PDF) so slightly less technical people can figure out how to work with the API." - which is literally what this tool is, with the added benefit of being publicly hosted.

I don't see how https://koumoul.com/openapi-viewer - which is also included on openapi.tools - is any different.

**Comment by daveshanley** [comment]
It looks almost exactly the same as Swagger UI? I don't know what the value is? What is this tool doing differently?

**Comment by InventivetalentDev** [comment]
FWIW this does work better on mobile.  

but I also don't care enough to bother discussing this any further, just wanted to share something that could be useful for others :)

**Pull request closed without merging**
