### PR TITLE
php openapi data validator

### PR DESCRIPTION
**Pull request by mieszkomalawski**

### CODE REVIEW

**Comment by philsturgeon** [comment]
Hey! This looks great @mieszkomalawski, thanks for taking the time to work on this, and submit it. There were a few things I wanted to check on before merging. 

## JSON Schema Divergence
How do you handle the [OpenAPI v3.0 divergence](https://philsturgeon.uk/api/2018/03/30/openapi-and-json-schema-divergence/), what with using a JSON Schema validator to validate OpenAPI v3.0? 

In JavaScript you can feed a metaschema to teach the JSON Schema validator how to handle OpenAPI specific content: https://github.com/OAI/OpenAPI-Specification/pull/1270

If you aren't doing this, then things might get a bit funky, with invalid JSON Schema functionality being used, or other unexpected behaviour. 

Other feedback:

- Could you use Markdown in the README so its readable?
- Could you put a simple example in the README so folks can understand it without clicking into `examples/`?
- your examples `info:` is missing `title` and `version` which should cause a validation error. 

``` yaml
info:
paths:
  /books:
    get:
      operationId: getBooks
      responses:
        '200':
          description: Fetch list of books
          content:
            application/json:
              schema:
                type: object
                required:
                  - name
                properties:
                  name:
                    type: string
                    nullable: false
                    example: "Vulcan lives"
                  tag:
                    type: string
                    example: "foo"
            application/xml:
              schema:
                type: object
                required:
                  - count
                properties:
                  count:
                    type: integer
openapi: 3.0.0
```

**Comment by mieszkomalawski** [comment]
Hi, thanks for all the feedback @philsturgeon 

1. This library handles divergence eg. nullable field is removed and null is added to type array etc.
2. I fixed README.md - it displays correctly (at least on gitlab)
3. Added example to README
4. Fixed tests specs

**Comment by mieszkomalawski** [comment]
Sorry, I did notice that README does not display correctly on packagist - I will fix that

**Comment by mieszkomalawski** [comment]
Fixed README so it displays correctly on packagist

**Comment by mieszkomalawski** [comment]
Changed link to gitlab instead packagist because packagist has some issues with linking images

**Comment by philsturgeon** [comment]
Thank you!

**Pull request merged**
