### PR TITLE
Add API Sprout mock server.

### PR DESCRIPTION
**Pull request by danielgtaylor**

### CODE REVIEW

**Comment by philsturgeon** [comment]
The timing on this could not have been better, you are a hero (once again). I'm giving it a try, and getting this:

```
$ docker pull danielgtaylor/apisprout
Using default tag: latest
latest: Pulling from danielgtaylor/apisprout
Digest: sha256:0b2ab61269e001e944383c26a81119236758717bca0b780f1a8a7b9a04f42ba6
Status: Image is up to date for danielgtaylor/apisprout:latest

$ docker run -p 8000:8000 apisprout http://example.com/my-api.yaml
Unable to find image 'apisprout:latest' locally
docker: Error response from daemon: pull access denied for apisprout, repository does not exist or may require 'docker login'.
```

I'd love to see it working before I merge this, any tips?

**Comment by philsturgeon** [comment]
Thank you. Next: trouble with docker and local files: 

```
▶ ls generated/specs/airlock/openapi.yml
generated/specs/airlock/openapi.yml

▶ docker run -p 8000:8000 danielgtaylor/apisprout generated/specs/airlock/openapi.yml
2018/07/26 18:30:12 open generated/specs/airlock/openapi.yml: no such file or directory
```

**Comment by danielgtaylor** [comment]
You can use Docker volumes to map local to in-container paths for this, e.g:

```sh
docker run -v ~/Projects/foo/openapi.yaml:/api.yaml -p 8000:8000 danielgtaylor/apisprout /api.yaml
```

Again I'll update the docs to include this in a few minutes, thanks for the feedback!

You can also download the compiled executable for your OS and run it locally. I envisioned the Docker image as being more useful in an environment like Kubernetes where you wouldn't have the file available locally.

**Comment by danielgtaylor** [comment]
Docs are updated, let me know if you have any other issues!

**Pull request merged**
