### PR TITLE
Update tools.yml

### PR DESCRIPTION
**Pull request by AndreasPvd**
Added an additional OpenAPI tool

### CODE REVIEW

**Comment by daveshanley** [comment]
This is not a tool, it's a press release.

**Comment by AP-G** [comment]
The link is the only page that currently exists for the tool. But if you want to take it out - ok. Then please change it just to https://www.gefeg.com/en/gefeg-fx.html

**Comment by daveshanley** [comment]
My problem is that there is nowhere to download the tool I can see, and this page: https://www.gefeg.com/en/gefeg-fx.html contains no mention of OpenAPI at all. 

If a product supports OpenAPI as a feature, that's great - but does it make it an OpenAPI tool that a developer can try out via SaaS or download?

Part of the purpose of this project is to curate high-quality tools that are focused only on OpenAPI and are available to use and consume by developers.

I don't know how a developer can consume this product without being an existing customer or needing to use this particular tool that also contains support for OpenAPI specs.

To me, it's like listing IntelliJ or VSCode as an OpenAPI tool - sure, they support OpenAPI, but are they OpenAPI tools? 
n my opinion.

**Comment by AP-G** [comment]
It is correct that you cannot simply download the tool. It is a closed source tool that you need to buy or that your need to contact the developing organisation in order to get a trial version. As it is not yet mentioned on the www.gefeg.com page, but only on the news.gefeg.com page it was that page I added in the tools.yml.

It is a tool that pureley focuses on the develoment of design time (not runtime) data models, syntaxes and - since around 18 months - OpenAPI specifications. The tool is widely used by standardisation organisations or businesses who need to document or specify their data structures. For instance the European automotive industry uses this tool to develop standardised OpenAPI specifications. Those specifications are then implemented with all kinds of different tools by developers. So the main target group of this tool is not the typical developer - although it could be interesting for them as well. It target group are the developers and (specification) designers that want to create OpenAPI specifications for B2B data exchange based on international standards. 
For instance the standardisation organisation of the United Nations (UN/CEFACT) just published a standard on how OpenAPI specifications should be developed in a B2B relationship. Together with this it published their (very huge) semantic reference data models for B2B data exchange in JSON schema and JSON-LD. All of this is done with the mentioned tool - design time only, no run time. And those data structures and data models (or any other locally defined one) can for instance be used directly in an OpenAPI specification for B2B communication. 

Summarizes, the tool is more comparable with the Swagger editor than with VSCode or comparable. Only that it additionally supports the creation of UML data models, EDIFACT, XML, JSON and JSON-LD and their use in defining OpenAPI specifications.

So is it correct that to your definition only open source tools can be of high-quality?

Again, what kind of information or re-writing of the definition do you need exactly to put this high-quality closed-source product on the list of OpenAPI tools of the category of GUI editors?

**Comment by daveshanley** [comment]
There is no hard and fast rule on commercial vs SaaS vs Open source - the only two things I am personally evaluating how close what is submitted can be defined as a 'tool' and how closely aligned it is with OpenAPI.

I personally feel that a larger tool that supports OpenAPI as a schema, is not really an OpenAPI tool per se, however there isn't a hard or fast definition of this anywhere for this project, so I don't want to become a gatekeeper here on this issue and prevent a useful tool being added to the index.

I would recommend that the link goes to the tool, vs the press release/blog post that talks about the tool enhancement. Once that change is made, we can merge it in.

**Comment by AndrewWalsh** [comment]
@AP-G following @daveshanley 's comments, there is no clear path to using this tool. Following updated guidelines and prior highly valid discussion, this particular PR will be closed. Opportunities remain for new PRs that feature clearer viability.

**Pull request closed without merging**
