### PR TITLE
Add Apitally

### PR DESCRIPTION
**Pull request by itssimon**
Adds Apitally, a REST API monitoring tool, to the *Monitoring* category, which currently features only Treblle.

Apitally uses OpenAPI to detect API endpoints and provides detailed endpoint insights in the dashboard, enriched with metadata from OpenAPI.

### CODE REVIEW

**Comment by AndrewWalsh** [comment]
Hi @itssimon ,

Could you please resolve the merge conflict? I think this looks viable.

However, could you please provide a more descriptive title aligned to the purpose of the tool? At present `Simple REST API monitoring tool that helps engineering and product teams understand how their APIs are being used.` doesn't describe your platform offering well or do it service.

E.g. (and this is just a suggestion, please do provide your own ;), something like
`Middleware for Node and Python frameworks integrated with a platform to help companies understand their APIs. Identifies endpoint latency, errors, usage, and other factors. Includes uptime monitoring for SLAs, and logging of individual requests.`

**Comment by itssimon** [comment]
Thanks for your feedback @AndrewWalsh! I've resolved the conflict and also updated the description based on your suggestion.

**Comment by AndrewWalsh** [comment]
@philsturgeon One more SaaS for the road?

**Comment by AndrewWalsh** [comment]
Thanks @itssimon for addressing the conflict and for your changes to the description. Merged.

**Pull request merged**
