### PR TITLE
Add openapi-backend node.js module

### PR DESCRIPTION
**Pull request by anttiviljami**
Hi!

Here's a new module I've just released on NPM. Would you consider adding this to your list? 

Github: https://github.com/anttiviljami/openapi-backend
NPM: https://www.npmjs.com/package/openapi-backend

Thanks in advance for your feedback!

### CODE REVIEW

**Comment by philsturgeon** [comment]
This looks really promising, but let's revisit this in a month or so after you've had a chance to iron things out. The initial commit was only 3 days ago, so I'd hesitate to rush this one in. 

I really like the sound of JSON Schema validation for requests and a lot of the other functionality you've listed. I'll be keeping a close eye on this one. :)

**Comment by anttiviljami** [comment]
Hi! It's been a month. :) Time to revisit? Not much has changed in terms of features, but perhaps some maturity can be seen as we are using this heavily in our own projects.

**Comment by philsturgeon** [comment]
@anttiviljami I love the direction and the features listed on the README. I've not dug into the code, but there's enough here for me to support linking to it :D 

Keep at it!

**Comment by anttiviljami** [comment]
Thank you so much! 🙌

**Pull request merged**
