### PR TITLE
Remain OpenAPI Studio listing

### PR DESCRIPTION
**Pull request by aaadel**
Would you please allow the addition of our OpenAPI studio listing in the  GUI editors section?

### CODE REVIEW

**Comment by matthewtrask** [comment]
Just curious, you only have exe files, which Im 99% sure is not able to run on Mac or Linux. Do you have dmg files available?

**Comment by aaadel** [comment]
Thank you for asking.
Currently we don't offer DMG files for direct download. But if you're using Eclipse (doesn't matter in which OS), you can install it as plugin via:                                                                                                     

1. Eclipse Marketplace: https://marketplace.eclipse.org/content/openapi-studio-rich-oas3-editor
2. Or our Eclipse update site: https://openapi-studio.com/updates/features/

**Comment by matthewtrask** [comment]
@aaadel thanks for the submission but we need to pass right now. Its not fair for us to assume everyone uses Eclipse or windows only. When you have DMG's available for Mac/Linux please let us know.

**Comment by aaadel** [comment]
In addition to Windows, We're currently supporting Mac and Linux installs as well:

https://remainsoftware.com/extranet/download-type/remain-openapi-studio-download

Would you please reconsider our  [Remain OpenAPI Studio](https://remainsoftware.com/docs/openapi/help/index.jsp#nav/0_0) listing?

**Comment by philsturgeon** [comment]
Thanks for the update. I cannot see much from those links, lots of broken links and where is the actual download link or product page? The docs arent looking so hot.

**Comment by aaadel** [comment]
Which one is broken???

Sign in and get access to download standalone Windows, Linux, or Mac executables.
https://remainsoftware.com/extranet/download-type/remain-openapi-studio-download

For eclipse users on Windows, Linux, or Mac, one may install plugins from the Eclipse Marketplace:
https://marketplace.eclipse.org/content/openapi-editor#group-details

For the docs, these are external wiki usage docs. They're also provided within our studio itself. They're quite exhaustive and covers all features of our OpenAPI studio pretty well.
Hot or not, is irrelevant. It's functional and works.

**Pull request closed without merging**
