### PR TITLE
Added Alphadoc

### PR DESCRIPTION
**Pull request by Stolkmeister**

### CODE REVIEW

**Comment by daveshanley** [comment]
Where is the tool? Another SaaS only paid documentation service.

**Comment by darrelmiller** [comment]
@daveshanley I don't have an opinion on whether this list should or shouldn't contain purely commercial tools, but if the decision is that that it should not, we should probably add a note somewhere about that.

**Comment by daveshanley** [comment]
My personal criteria for a tool:

- It's Downloadable

The conversation here is really that it's not that SaaS-only services should be excluded from the list. Still, they should be put into a very specific category and not be peppered along with all the other hard-working volunteers who build free and open-source tools for no money (which is the spirit of this project).

We need to re-categorize or add a new feature to distinguish between commercial and non-commercial.

**Comment by philsturgeon** [comment]
To be fair to @Stolkmeister here, that is a fair requirement but one that's so far not been applied to the others. I'll merge this, but let's get Commercial / OSS tags up so we can be fair about it.

**Review by philsturgeon — APPROVED** [review]

**Pull request merged**
