### PR TITLE
Add OpenAPI Style Validator to the list of available tool

### PR DESCRIPTION
**Pull request by JFCote**
Hi! 

Just wanted to add our project to your awesome list! Thanks!

### CODE REVIEW

**Comment by philsturgeon** [comment]
Hey there @JFCote! Great to see more folks interested in solving linting and design consistency. :) 

I saw the motivations section: 

> This project was started because when I tried SwaggerHub (which is the paid version of the swagger toolkit), they had something similar, but it was proprietary. I didn't want to pay for the service so I created this project in my free times. I did not validate lately if they still have this feature.

I think maybe you might have been working on this before Speccy or [Spectral](https://github.com/stoplightio/spectral) were started looking at some of the commit timestamps, but at this time I wonder if there is much value in sending people to this in its current form? It seems mostly about booleon options for each built in rule, but no custom rulesets, custom rules, or custom functions? 

It would be _awesome_ to see if we could collaborate a bit on getting rulesets and rules aligned with Spectral, so that things could be a bit more plug and play. The benefit here would be supporting a growing number of purpose-built rulesets, like AsyncAPI, AWS, etc: https://github.com/openapi-contrib/style-guides/

Would you be interested in working on that?

**Comment by JFCote** [comment]
Hi @philsturgeon 
To be honest, I discovered Spectral today while browsing your list. :) This is definitely something very similar to what we are doing. My project was started a long time ago for my own team only and had been given a second life by joining OpenApi Tools a couple of months ago. At the time of creation, there was no other alternatives. 

One main difference I see is that Spectral is done in Typescript which make it difficult to integrate in Java project. Also, we are about to release the gradle plugin (and later, the maven one) which will give the ability to use the linter in any gradle build.

As for the idea of the rules, this is definitely something that we could work on. @jmini and I are the main contributors and we work on this on our free time, so I don't expect it to be released anytime soon but we could aim to align with something similar.

One last thing, I think even if it has less feature that Spectral, our project is interesting in its own way because it is simple. Most people will not even look at the default rules or change them (even if it's only booleans). Some of them might change the default for their special case. A very small amount will try to create custom rules.

Thanks

**Comment by philsturgeon** [comment]
I'm glad joining them has given it a breath of fresh air!

I was working on Speccy and Spectral, both had a very similar story: users were demanding custom rulesets and rules, then when they got that they wanted custom functions, and when they got that they want to let folks ignore certain rules, or change the priority because they cant fix it right now, or ignore a specific instance of a rule (https://github.com/stoplightio/spectral/issues/747) in one file but keep it going elsewhere. 

The more people start to use this tool, the more use cases are gonna show up. 

I support having another tool around which is easy for the Java people, but you're definitely going to get inundated with requests if you keep the current approach. 

If you ever want to talk about custom rulesets, rules, etc, them maybe you could swing by https://slack.apisyouwonthate.com. New folks always welcome! :D

**Comment by JFCote** [comment]
@philsturgeon Thanks! Will definitely do!

**Pull request merged**
