### PR TITLE
Added RapiDoc a Custom-Element for Open API spec View

### PR DESCRIPTION
**Pull request by mrin9**
[RapiDoc Documentation](https://mrin9.github.io/RapiDoc/)

### CODE REVIEW

**Comment by mrin9** [comment]
`bump`

**Comment by matthewtrask** [comment]
this looks cool for me, but I'll let Phil double check.

**Comment by philsturgeon** [comment]
Lgtm

--
Phil Sturgeon
@philsturgeon

**Comment by mrin9** [comment]
@matthewtrask I hope this can be merged now ?

**Comment by matthewtrask** [comment]
thanks!

**Pull request merged**
