### PR TITLE
Add oval

### PR DESCRIPTION
**Pull request by whitlockjc**
Add [oval](https://github.com/whitlockjc/oval) to the list.

### CODE REVIEW

**Comment by whitlockjc** [comment]
`oval` is a CLI built on top of `sway`, but it is a separate thing.  I'll resolve the merge conflict, and know that it too has a link to the `sway` v3 progress issue.

**Comment by philsturgeon** [comment]
So it seems like sway is doing essentially the same job as oas-kit, and oval is aiming to do the same thing as speccy? It seems like we're duplicating a lot of work here where we could be working together. Could we try to work together on the linting logic at least? I have been talking to a few folks about creating a standardized lint rule interface, which oas-linter, speccy, stoplight, etc could all follow. :)

**Comment by whitlockjc** [comment]
Trust me, I think the issue is that people didn't know about these.  `sway` has been around since before all of these other projects.  And `oval` is just a sway-based CLI to replace `swagger-tools`' CLI.

**Comment by philsturgeon** [comment]
I know sway was around before oas-kit but you only just got up to OpenAPI v3 :D 

The point was more about how oval seems to be doing the same thing as speccy, and we could probably share some of the load. Building a linter isn't the fast track to fame and fortune so we don't need to be in competition, and I'd absolutely love the help, as would Mike. 

Theeeen I was pointing out that if thats no good, maybe we could put our heads together on what we'd want out of a shared linting rules definition format. The end goal being a "linter marketplace" where people can share and distribute their rules, like "airbnb eslint", etc.

**Comment by whitlockjc** [comment]
Yeah, but people contributed to existing tooling instead of reinventing the wheel, it would be great and OASv3.x support might had come from the community.  I agree it would be great to combine efforts, but I've never pushed back on working with people so I'm not sure why people felt the need to reinvent the wheel anyways.  In fact, `swagger-tools` precedes `sway` and it had a CLI for v1.x and v2.x validation.

**Comment by philsturgeon** [comment]
I feel like we're having different conversations. Could you please re-read my last message and focus on the part where I am not complaining about sway existing in any way, or attack you or your projects at all. 😄  

I am talking about oval, and a potential shared format.

**Comment by whitlockjc** [comment]
Oh, I wasn't taking it that way.  :)  The point was more along the lines where I've wanted what you're asking for from day one and I've been surprised at competing tooling coming out after those existed.  It was me agreeing by giving a history lesson.  ;)

**Comment by philsturgeon** [comment]
Oh good! :D 

I'll get in touch when I've got some ideas for a linter format and we can take it from there?

**Comment by whitlockjc** [comment]
Sounds good.  I personally like the idea of `eslint`-style approach.  I would love to see collaboration on all things, not just a shared format.  I'd love to see collaboration on the tools themselves, combining them into a best-of-breed instead of tools that overlap a ton with people building them in silos.  Shared formats, centralized projects, etc.

**Comment by whitlockjc** [comment]
I think that might be where the disconnect was.  Not only did you think I was getting defensive, but I assure you I wasn't, but I was talking about bigger picture collaboration instead of just solely on a similar format for competing tools.  Make sense?

**Comment by philsturgeon** [comment]
Ok, I'll try to think about how we can approach that. 

@MikeRalphson and @James-Messinger would you folks be into trying to figure out a grand collaboration of some competing tools? The go community is going through the same thing. 

We could make an `openapi-js` organization and try to create one tool for each, taking the best bits of all of them?

**Comment by whitlockjc** [comment]
I will be honest, I'm tired of maintaining everything I do by myself.  I don't care whose tools we collapse into, I just think we'd be better off combining forces.  This isn't about who wins, but about the community we could build by doing this.

**Comment by James-Messinger** [comment]
Agreed.  I've been struggling to maintain all of my libraries lately, due to work and family commitments.  There aren't enough hours in the day to do it alone.

One of the first steps would be to agree on what exactly needs to be built, and how it should be broken up into distinct packages.  One lesson I've learned from [swagger-parser](https://github.com/James-Messinger/swagger-parser#swaggeropenapi-parser)  and [swagger-express-middleware](https://github.com/James-Messinger/swagger-express-middleware/#swagger-express-middleware) is that cramming a bunch of somewhat-related functionality into a single library quickly becomes bloated, unmaintainable, and impossible to test.  I think Sway and OAS-Kit may suffer from the same thing.  I'd love to start over and break swagger-parser into 3 or 4 separate packages, and swagger-express-middleware could easily be 6 separate packages - one for each middleware.  Not only would this be more maintainable, but it would also make each library more flexible and useful for a wider variety of use-cases. 

Another thing to discuss is environment targets.  Ideally, most of the openapi-js packages would support both Node and web browsers (a.k.a. "polymorphic", a.k.a. "universal javascript").  Many NPM packages (mine included) are guilty of only supporting web browsers as an afterthought, often resulting in *huge* browser bundles that include lots of Node-specific code that isn't relevant/necessary in a browser environment.  It could also be cool for the Node versions of the packages to also be distributed as standalone executables, ala [pkg](https://github.com/zeit/pkg), [nexe](https://github.com/nexe/nexe), [encloseJS](http://enclosejs.com/), etc.  This would make them usable by _anyone_, not just Node developers, which could help eliminate the need for redundant, language-specific versions of every OAS tool.

I've had a to-do list item for a while now to do a complete rewrite of my libraries for OAS 3, taking the above considerations into account, along with many other lessons I've learned over the past few years of maintaining these projects.  I'm planning to do the rewrite in TypeScript, because many of my users and contributors have asked for good type definitions and tooling support.  I'd gladly start this under the banner of "openapi-js" if that sounds good.

**Comment by whitlockjc** [comment]
I agree with @James-Messinger.  For a little history, what's funny is that `sway` was the result of `swagger-tools` doing too much as an API, CLI and Middleware in one.  And the hopes were to break `swagger-tools` up into an API _(`sway`)_, CLI _(`oval`)_ and eventual middleware projects.  I do agree that `sway` is suffering from doing too much, not necessarily a bad thing, and there is an [issue](https://github.com/apigee-127/sway/issues/187) to break it up into smaller components.  Now might make sense to align so we don't do the same work.

I can tell you that Google is **unofficially** _"sponsoring"_ `sway` development since we use it in some of the Apigee Edge tooling.  That means we might be able to benefit from this.  This isn't a bid to focus on `sway`, just something that might play a role in making a decision since we all seem to be a little time strapped.

**Comment by philsturgeon** [comment]
Hey folks, just wanted to bump this thread and check back in with some updates. 

I've started working at [Stoplight](http://stoplight.io), which manages Spectral. It's being used for a lot of our cool paid stuff so its in much more active development than Speccy was, and is designed to work with anything, not just OpenAPI v3.0 spec files. 

Speccy is still being maintained but most efforts are going into Spectral. 

@whitlockjc did you make much progress on Oval? Do you fancy checking out Spectral to see if its a thing we can all work together on? :) 

How are folks doing with their various pieces of sway/oas-kit/generic JS parsers and such? Should we look into making an openapi-js organization as a place for us to collaborate and work on code that is not tied to a specific company?

**Comment by whitlockjc** [comment]
`oval` is feature complete for a `swagger-tools validate` replacement but not much in the way of what I originally hoped of an `eslint`-style tool.  I am all for working on things together instead of separate, I've been advocating this for quite some time.

**Pull request merged**
