### PR TITLE
Testing: Add Tcases for OpenAPI

### PR DESCRIPTION
**Pull request by kerrykimbrough**

### CODE REVIEW

**Comment by matthewtrask** [comment]
@kerrykimbrough can you update the github link just to point at the repository and not a specific file? thanks!

**Comment by kerrykimbrough** [comment]
I chose this URL because it describes this specific tool, which is the only module related to OpenAPI within the repo. I was concerned that someone landing at the top of the repo might not find it. But if you think a top-level link is better I'll change it.

**Comment by kerrykimbrough** [comment]
Or maybe use the "link" property to point to the README file?

**Comment by matthewtrask** [comment]
eh it should be fine, thanks!

**Pull request merged**
