### PR TITLE
Swagger mock server

### PR DESCRIPTION
**Pull request by strider2038**
Hello! Please, add my mock server to the list of tools.

### CODE REVIEW

**Comment by strider2038** [comment]
@philsturgeon @MikeRalphson Hello! Please, add my mock server to the list of tools.

**Comment by matthewtrask** [comment]
this looks good to me. @philsturgeon?

**Comment by philsturgeon** [comment]
@strider2038 hey there! Are you associated with SmartBear in some sort of official capacity? They own the trademark Swagger, and its been years since the spec was renamed to OpenAPÎ, so other folks should be naming their products after OpenAPI not Swagger. :)

**Comment by matthewtrask** [comment]
@strider2038 hey any chance you can address the feedback here?

**Comment by matthewtrask** [comment]
@strider2038 hey Im going to close this for now. If you can look at our feedback and update appropriately, please reopen the PR and tag me.

**Pull request closed without merging**
